version: '3'
services:
  reserva:
    build: .
    expose:
      - "80"
    volumes:
      - ./app:/var/www/html
    environment:
      - HOST_NAME=gp1f5a14
  lb:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - reserva
    ports:
      - "8000:8000"
